modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Mechanax/PseudoSorcery/issues"

[[mods]]
modId="pseudosorcery"
displayName="PseudoSorcery"
version="${version}"
authors="Mechana"
description='''
A magic mod based on various pseudosciences around the world.
'''

[[dependencies.pseudosorcery]]
    modId="forge"
    mandatory=true
    versionRange="[28.2.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pseudosorcery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,)"
    ordering="NONE"
    side="BOTH"