modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Mechanax/Crystal/issues"

[[mods]]
modId="crystal"
displayName="Crystal"
version="${version}"
authors="Mechana"
description='''
The start of something big
'''

[[dependencies.crystal]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.87,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.crystal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"